---
- hosts: local
  gather_facts: yes
  tasks:
    - name: Ping test
      ansible.builtin.ping:

    - name: Display execution message
      ansible.builtin.debug:
        msg: "Ansible playbook pulled from GitHub and executed via Jenkins!"
