---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Ping target
      ansible.builtin.ping:

    - name: Print success message
      ansible.builtin.debug:
        msg: "Pipeline execution successful!"
